### ISSUE TITLE
Clicking outside the modal should close it.

### ISSUE THREAD

**Issue by leandroz** [roberthovhannisyan/PhoneGap-Plugin-ListPicker#2]
When you are using the native select element, when you click outside the modal is close.
I think that this should be the default behavior for this one too!

**Comment by roberthovhannisyan** [comment]
Hi @leandroz,
I have checked your issue with the latest version of the plugin on several androids and when you click outside the dialog it is dismissed and error javascript function (if it is provided) is called. Please, make sure you are using latest version of the plugin. If your issue is still there, please, provide more details on the version of android and device.

**Comment by leandroz** [comment]
Sorry @roberthovhannisyan is working ok!
